server:
  port: ${SERVER_PORT:8888}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

spring:
  application:
    name: config-service
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config-repo

management:
  endpoints:
    web:
      exposure:
        include: health,info
